name: Reusable Spike
on:
  workflow_call:
    outputs:
      result:
        description: "Result of all workflow runs"
        value: ${{ jobs.workflow-diagnostics.outputs.result }}
    inputs:
      payload:
        description: "Name event that started the workflow"
        required: true
        type: string
      skip:
        description: "Whether to skip the workflow"
        required: true
        default: false
        type: boolean

jobs:
  workflow-diagnostics:
    name: "Diagnostics"
    if: inputs.skip == false
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.results.outputs.result }}
    steps:
      - name: Inputs and Environment
        run: |
          exit 1

  workflow-finish:
    name: "Finish"
    needs: [workflow-diagnostics]
    if: always()
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.results.outputs.result }}
    steps:
      - name: Inputs and Environment
        run: |
          exit 0
