name: Reusable Spike
on:
  workflow_call:
    outputs:
      first-result:
        description: "Result of the first workflow run"
        value: ${{ jobs.workflow-diagnostics.outputs.first-result }}
      second-result:
        description: "Result of the second workflow run"
        value: ${{ jobs.workflow-diagnostics.outputs.second-result }}
    inputs:
      name:
        description: "Name of the workflow"
        required: true
        type: string
      skip:
        description: "Whether to skip the workflow"
        required: true
        default: false
        type: boolean

jobs:
  workflow-diagnostics:
    if: inputs.skip == false
    runs-on: ubuntu-latest
    outputs:
      first-result: ${{ steps.results.outputs.first-result }}
      second-result: ${{ steps.results.outputs.second-result }}
    steps:
      - name: Inputs and Environment
        run: |
          echo ""
          echo "inputs: ${{ toJSON(inputs) }}"
          echo ""
          echo "env: ${{ toJSON(env) }}"
          echo ""
          echo "env: ${{ toJSON(github.event.pull_request) }}"
          echo ""
      - name: "Results"
        id: results
        run: |
          first_result=true
          second_result=true
          echo "first-result=$first_result" >> $GITHUB_OUTPUT
          echo "second-result=$second_result" >> $GITHUB_OUTPUT