# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike Workflow run
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Spike
    types: completed

concurrency:
  group: workflow-run-${{ github.event.workflow_run.head_branch || github.ref }}

jobs:
  spike-workflow-run:
    name: Spike workflow run
    runs-on: ubuntu-latest
    steps:
      - name: "Check contents"
        run: |
          echo "Head branch - github.event.workflow_run.head_branch"
          echo "${{ github.event.workflow_run.head_branch }}"
          echo "====================="
          echo "Github ref - github.ref"
          echo "${{ github.ref }}"
          echo "====================="
          echo "${{ toJSON(github.event.workflow_run) }}"
