# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  first-job:
    name: "First job"
    runs-on: ubuntu-latest
    steps:
      - name: "Result"
        run: |
          githubEventPayload=${{ toJSON(github.event) }}
          echo "github.event is $githubEventPayload"
          echo "github.ref is ${{ github.ref }}"
          echo "github.head_ref is ${{ github.head_ref }}"
          echo "github.head_branch is ${{ github.head_branch }}"

  spike-reusable-workflow:
    name: "Spike workflow - reusable"
    uses: ./.github/workflows/spike-reusable-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - skip: false
            payload: ${{ toJSON(github.event) }}
    with:
      skip: ${{ matrix.skip }}
      payload: ${{ matrix.payload }}
