# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  spike-workflow:
    name: Spike workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ⬇️ Downloading test artifacts
        id: download-test-artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: test-artifacts*
          path: artifacts-path

      - name: "Check contets"
        run: |
          echo "This is the download path for artifacts: ${{ steps.download-test-artifacts.outputs.download-path }}"

  spike-reusable-workflow:
    name: "Spike workflow - reusable"
    uses: ./.github/workflows/spike-reusable-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - skip: false
            name: first
          - skip: false
            name: second
    with:
      skip: ${{ matrix.skip }}
      name: ${{ matrix.name }}

  spike-workflow-result:
    name: Spike workflow - result
    runs-on: ubuntu-latest
    needs: [spike-reusable-workflow]
    outputs:
      metadata: ${{ steps.create-metadata.outputs.metadata }}
    if: always()
    steps:
      - name: "Create metadata"
        id: create-metadata
        run: |
          echo "Result value is ${{ needs.spike-reusable-workflow.outputs.result }}"
          echo "metadata={ \
            \"span-id\":\"${{ needs.spike-reusable-workflow.outputs.result }}\", \
            \"trace-id\":\"${{ needs.spike-reusable-workflow.outputs.result }}\", \
            \"activity-log\":\"${{ needs.spike-reusable-workflow.outputs.result }}\", \
            \"telemetry-artifact-id\":\"${{ needs.spike-reusable-workflow.outputs.result }}\" \
          }" >> $GITHUB_OUTPUT

  check-contents:
    name: "Check contets"
    needs: [spike-workflow-result]
    uses: ./.github/workflows/spike-reusable-workflow.yml
    secrets: inherit
    with:
      skip: false
      name: ${{ fromJSON(needs.spike-workflow-result.outputs.metadata).trace-id }}
