name: Reusable Spike
on:
  workflow_call:
    outputs:
      result:
        description: "Result of all workflow runs"
        value: ${{ jobs.workflow-diagnostics.outputs.result }}
    inputs:
      payload:
        description: "Name event that started the workflow"
        required: true
        type: string
      skip:
        description: "Whether to skip the workflow"
        required: true
        default: false
        type: boolean

jobs:
  workflow-diagnostics:
    if: inputs.skip == false
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.results.outputs.result }}
    steps:
      - name: Inputs and Environment
        run: |
          pull_request=$(echo '${{ inputs.payload }}' | jq '.pull_request.number')
          echo "The pull request is: $pull_request"
          echo "========================="
          exit 0
