# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  first-job:
    name: "First job"
    runs-on: ubuntu-latest
    steps:
      - name: "Result"
        run: |
          exit 0
  second-job:
    name: "Second job"
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: "Result"
        run: |
          exit 1
  third-job:
    name: "Third job"
    runs-on: ubuntu-latest
    if: ${{ needs.second-job.result != 'cancelled' }}
    needs: second-job
    steps:
      - name: "Result"
        run: |
          echo "Third job ran"