name: Reusable Spike
on:
  workflow_call:
    outputs:
      result:
        description: "Result of all workflow runs"
        value: ${{ jobs.workflow-diagnostics.outputs.result }}
    inputs:
      name:
        description: "Name of the workflow"
        required: true
        type: string
      skip:
        description: "Whether to skip the workflow"
        required: true
        default: false
        type: boolean

jobs:
  workflow-diagnostics:
    if: inputs.skip == false
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.results.outputs.result }}
    steps:
      - name: Inputs and Environment
        run: |
          echo ""
          echo "inputs: ${{ toJSON(inputs) }}"
          echo ""
          echo "env: ${{ toJSON(env) }}"
          echo ""
          echo "env: ${{ toJSON(github.event.pull_request) }}"
          echo ""
      - name: "Results"
        id: results
        run: |
          echo "Current result is ${{ steps.results.outputs.result }}"
          result=${{ inputs.name }}
          echo "Result is $result"
          echo "result=$result" >> $GITHUB_OUTPUT