# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  spike-reusable-workflow:
    name: "Spike workflow - reusable ${{ inputs.skip }}"
    uses: ./.github/workflows/spike-reusable-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        include:
          - skip: false
            payload: ${{ toJSON(github.event) }}
    with:
      skip: ${{ matrix.skip }}
      payload: ${{ matrix.payload }}

  spike-result:
      name: "Spike workflow - result"
      needs: [spike-reusable-workflow]
      steps:
        name: "Result"
        run: |
          echo 0