# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  spike-workflow:
    name: Spike workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Check contets"
        run: |
          echo "This is a spike workflow step."
          echo "${{ toJson(github.event) }}"
          ls -la .github/workflows

  spike-reusable-workflow:
    name: "Spike workflow - reusable"
    uses: ./.github/workflows/spike-reusable-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - skip: false
            name: first
          - skip: false
            name: second
    with:
      skip: ${{ matrix.skip }}
      name: ${{ matrix.name }}

  spike-workflow-result:
    name: Spike workflow - result
    runs-on: ubuntu-latest
    needs: [spike-reusable-workflow]
    if: failure()
    steps:
      - name: "Fail"
        run: exit 1
