# Keep this as 'Spike' and it won't pollute the list of workflows in the GitHub UI
name: Spike
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  spike-workflow:
    name: Spike workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Check contets"
        run: |
          githubEventPayload=${{ toJSON(github.event }}
          echo "github.event is $githubEventPayload"

  spike-reusable-workflow:
    name: "Spike workflow - reusable"
    uses: ./.github/workflows/spike-reusable-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: true
      matrix:
        include:
          - skip: false
            payload: ${{ toJSON(github.event) }}
    with:
      skip: ${{ matrix.skip }}
      payload: ${{ matrix.payload }}
